### ISSUE TITLE
Why is the component a Module?

### ISSUE THREAD

**Issue by maxxer** [YetOpen/yii2-usuario-ldap#1]
From: https://gitlab.com/yetopen/yii2-usuario-ldap/-/issues/1

In the example config you configure a component, but the class is a `Module`.

Shouldn't that be either a module OR a class extended from Component?

CC @schmunk42

**Comment by mp1509** [comment]
Probably the best approach would be to leave the Module to store the LDAP configuration and the various parameters and a bootstrap class that adds the events that implements [yii\base\BootstrapInterface](https://www.yiiframework.com/doc/api/2.0/yii-base-bootstrapinterface).

**Comment by maxxer** [comment]
5d110cf4
